GET http://localhost:8888/api?itemId=99

###


POST http://localhost:8888/api
Content-Type: application/json

{
  "id": 199,
  "name": "test"
}

###

PUT http://localhost:8888/api
Content-Type: application/json

{
  "id": 199,
  "name": "test"
}

###


DELETE http://localhost:8888/api
Content-Type: application/json

{
  "id": 199,
  "name": "test"
}

###


POST http://localhost:8888/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="DocumentUpload"; filename="fileToUpload.txt"

< fileToUpload.txt
--WebAppBoundary--

###

GET http://localhost:8888/download

###


POST http://localhost:8888/transform
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="DocumentUpload"; filename="fileToUpload.txt"

< fileToUpload.txt
--WebAppBoundary--

###


GET http://localhost:8888/logs

###


GET http://localhost:8888/delay?delay=5000

###
