GET http://localhost:8888/api?itemId=99

###


POST http://localhost:8888/api
Content-Type: application/json

{
  "name": "test",
  "id": 199
}

###


POST http://localhost:8888/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="field-name"; filename="fileToUpload.txt"

< C:\Users\francisco.sanchez\Documents\IdeaProjects\spring-test\fileToUpload.txt
--WebAppBoundary--

###

GET http://localhost:8888/download

###
